/*
 * This file was generated automatically by xsubpp version 1.9508 from the
 * contents of Trn.xs. Do not edit this file, edit Trn.xs instead.
 *
 *	ANY CHANGES MADE HERE WILL BE LOST!
 *
 */

#line 1 "Trn.xs"
#include "EXTERN.h"
#include "perl.h"
#include "XSUB.h"

#include </home/rds/include/rds_trn.h>

static int
not_here(char *s)
{
    croak("%s not implemented on this architecture", s);
    return -1;
}

static double
constant(char *name, int arg)
{
    errno = 0;
    switch (*name) {
    }
    errno = EINVAL;
    return 0;

not_there:
    errno = ENOENT;
    return 0;
}


#line 39 "Trn.c"
XS(XS_RDS__Trn_constant); /* prototype to pass -Wmissing-prototypes */
XS(XS_RDS__Trn_constant)
{
    dXSARGS;
    if (items != 2)
	Perl_croak(aTHX_ "Usage: RDS::Trn::constant(name, arg)");
    {
	char *	name = (char *)SvPV_nolen(ST(0));
	int	arg = (int)SvIV(ST(1));
	double	RETVAL;
	dXSTARG;

	RETVAL = constant(name, arg);
	XSprePUSH; PUSHn((double)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_RDS__Trn_register); /* prototype to pass -Wmissing-prototypes */
XS(XS_RDS__Trn_register)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: RDS::Trn::register(name)");
    {
	char *	name = (char *)SvPV_nolen(ST(0));

	trn_register(name);
    }
    XSRETURN_EMPTY;
}

XS(XS_RDS__Trn_Alert); /* prototype to pass -Wmissing-prototypes */
XS(XS_RDS__Trn_Alert)
{
    dXSARGS;
    if (items < 1)
	Perl_croak(aTHX_ "Usage: RDS::Trn::Alert(fmt, ...)");
    {
	char *	fmt = (char *)SvPV_nolen(ST(0));
	int	RETVAL;
	dXSTARG;

	RETVAL = Alert(fmt);
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_RDS__Trn_Trace); /* prototype to pass -Wmissing-prototypes */
XS(XS_RDS__Trn_Trace)
{
    dXSARGS;
    if (items < 1)
	Perl_croak(aTHX_ "Usage: RDS::Trn::Trace(fmt, ...)");
    {
	char *	fmt = (char *)SvPV_nolen(ST(0));
	int	RETVAL;
	dXSTARG;

	RETVAL = Trace(fmt);
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_RDS__Trn_Inform); /* prototype to pass -Wmissing-prototypes */
XS(XS_RDS__Trn_Inform)
{
    dXSARGS;
    if (items < 1)
	Perl_croak(aTHX_ "Usage: RDS::Trn::Inform(fmt, ...)");
    {
	char *	fmt = (char *)SvPV_nolen(ST(0));
	int	RETVAL;
	dXSTARG;

	RETVAL = Inform(fmt);
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}

#ifdef __cplusplus
extern "C"
#endif
XS(boot_RDS__Trn); /* prototype to pass -Wmissing-prototypes */
XS(boot_RDS__Trn)
{
    dXSARGS;
    char* file = __FILE__;

    XS_VERSION_BOOTCHECK ;

        newXS("RDS::Trn::constant", XS_RDS__Trn_constant, file);
        newXS("RDS::Trn::register", XS_RDS__Trn_register, file);
        newXS("RDS::Trn::Alert", XS_RDS__Trn_Alert, file);
        newXS("RDS::Trn::Trace", XS_RDS__Trn_Trace, file);
        newXS("RDS::Trn::Inform", XS_RDS__Trn_Inform, file);
    XSRETURN_YES;
}

