# This file describes the network interfaces available on your system
# For more information, see netplan(5).
network:
  version: 2
  renderer: networkd
  ethernets:
    enp1s0:
      dhcp4: yes
    enp4s3:
      dhcp4: no
      dhcp6: no
      addresses: [192.168.1.100/24]
      optional: true
