# .bash_profile

# Get the aliases and functions
if [ -f ~/.bashrc ]; then
	. ~/.bashrc
fi

# User specific environment and startup programs
ulimit -c unlimited

PATH=$HOME/bin:$PATH
PATH=$HOME/app/bin:$PATH

CLASSPATH=$HOME/lib/*
CLASSPATH=$HOME/app/lib/*:$CLASSPATH
CLASSPATH=.:$CLASSPATH

LIBPATH=/home/rds/lib:$LIBPATH

export PATH
export CLASSPATH
export LIBPATH

unset USERNAME

