#!/bin/bash

NODATA_TABLES="
   _adminLog
   cartonLog
   counts_old
   eventLog
   execute
   notifications
"
DATADIR=$HOME/app/data
DUMP="mysqldump --order-by-primary --skip-extended-insert --hex-blob -urds -prds rds"

mkdir -p $DATADIR/tables
mkdir -p $DATADIR/views
mkdir -p $DATADIR/routines

mysql -s -urds -prds rds -e "SHOW FULL TABLES" | while read tablename tabletype; do
   if [ "$tabletype" == "VIEW" ]; then
      echo "view" $tablename
      $DUMP -d $tablename > $DATADIR/views/$tablename.sql
   else
      no_data=0
      if [ "$NODATA_TABLES" != "" ];
      then
         for t in $NODATA_TABLES
         do
            if [ "$tablename" == "$t" ] ; then
               no_data=1
            fi
         done
      fi

      if [ "$no_data" == "1" ] ; then
         echo "nodata table" $tablename
         $DUMP -d $tablename > $DATADIR/tables/$tablename.sql
      else
         echo "table" $tablename
         $DUMP $tablename > $DATADIR/tables/$tablename.sql
      fi
   fi
done

echo "routines"
$DUMP -d -t --routines > $DATADIR/routines/routines.sql

