#!/bin/bash

#
# count_compress
# This script aggregates production counts in the counts table.
#

###
MINUTE_DAYS=1
HOUR_DAYS=30
DAY_DAYS=90
DELETE_DAYS=180

echo "Compressing counts table..."

# delete everything older than n days old
echo "  purging counts table"
time /usr/bin/mysql -urds -prds -Drds -e "DELETE FROM counts WHERE stamp<SUBDATE(NOW(),INTERVAL $DELETE_DAYS DAY)" 

# add a column for the rounded datetime values
echo "  modifying counts table"
time /usr/bin/mysql -urds -prds -Drds -e "ALTER TABLE counts ADD stamp_aggregate datetime"

# initialize the rounded timestamp
echo "  initializing aggregate timestamp"
time /usr/bin/mysql -urds -prds -Drds -e "UPDATE counts SET stamp_aggregate=stamp"

# round everything older than n days to the nearest minute
echo "  rounding timestamps to the nearest minute"
time /usr/bin/mysql -urds -prds -Drds -e "UPDATE counts SET stamp_aggregate=stamp_aggregate-INTERVAL EXTRACT(second FROM stamp) SECOND,msec=0 WHERE stamp<SUBDATE(NOW(),INTERVAL $MINUTE_DAYS DAY)"

# round everything older than n days to the nearest hour 
echo "  rounding timestamps to the nearest hour"
time /usr/bin/mysql -urds -prds -Drds -e "UPDATE counts SET stamp_aggregate=stamp_aggregate-INTERVAL EXTRACT(minute FROM stamp) MINUTE WHERE stamp<SUBDATE(NOW(),INTERVAL $HOUR_DAYS DAY)" 

# round everything older than n days to the nearest day 
echo "  rounding timestamps to the nearest day"
time /usr/bin/mysql -urds -prds -Drds -e "UPDATE counts SET stamp_aggregate=stamp_aggregate-INTERVAL EXTRACT(hour FROM stamp) HOUR WHERE stamp<SUBDATE(NOW(),INTERVAL $DAY_DAYS DAY)"

# aggregate counts by stamp_aggregate
echo "  aggregating counts"
time /usr/bin/mysql -urds -prds -Drds -e "CREATE TABLE counts_new (stamp datetime NOT NULL DEFAULT '0000-00-00 00:00:00', value double(17,0) NOT NULL default 0, KEY code_stamp (code,stamp)) SELECT code,stamp_aggregate AS stamp,msec,SUM(value) AS value FROM counts GROUP BY code,stamp_aggregate"

# rotate the counts tables
echo "  rotating counts tables"
/usr/bin/mysql -urds -prds -Drds -e "DROP TABLE IF EXISTS counts_old"
/usr/bin/mysql -urds -prds -Drds -e "ALTER TABLE counts RENAME counts_old"
/usr/bin/mysql -urds -prds -Drds -e "ALTER TABLE counts_new RENAME counts"

echo "  done"
