#!/bin/bash

HOST='hostname'
MIN_ORDINAL=100


echo "restarting trak and associated applications on $HOST"

rc.trak
sleep 3

rpload
echo "QUERY: UPDATE launch SET operation = 'trigger' WHERE host = '$HOST' AND ordinal >= $MIN_ORDINAL AND mode = 'daemon'"
/usr/bin/mysql -hdb -urds -prds rds -e "UPDATE launch SET operation = 'trigger' WHERE host = '$HOST' AND ordinal >= $MIN_ORDINAL AND mode = 'daemon'"

