network:
  version: 2
  renderer: networkd
  ethernets:
    enp0s31f6:
      dhcp4: no
      dhcp6: no
      optional: true
    enp1s0:
      dhcp4: no
      dhcp6: no
      addresses: [172.27.13.2/24]
      gateway4: 172.27.13.1
      nameservers:
         addresses: [8.8.8.8,8.8.4.4]
    enp2s0:
      dhcp4: no
      dhcp6: no
      addresses: [192.168.1.100/24]
      optional: true
    enp3s0:
      dhcp4: no
      dhcp6: no
      addresses: [192.168.100.1/24]
      optional: true

